set(_CATKIN_CURRENT_PACKAGE "waffle_lab")
set(waffle_lab_VERSION "0.0.0")
set(waffle_lab_MAINTAINER "siddhesh <siddhesh@todo.todo>")
set(waffle_lab_PACKAGE_FORMAT "2")
set(waffle_lab_BUILD_DEPENDS "nav_msgs" "rospy" "std_msgs" "geometry_msgs" "tf" "message_generation")
set(waffle_lab_BUILD_EXPORT_DEPENDS "nav_msgs" "rospy" "std_msgs" "tf" "geometry_msgs")
set(waffle_lab_BUILDTOOL_DEPENDS "catkin")
set(waffle_lab_BUILDTOOL_EXPORT_DEPENDS )
set(waffle_lab_EXEC_DEPENDS "nav_msgs" "rospy" "std_msgs" "geometry_msgs" "message_runtime" "tf")
set(waffle_lab_RUN_DEPENDS "nav_msgs" "rospy" "std_msgs" "geometry_msgs" "message_runtime" "tf")
set(waffle_lab_TEST_DEPENDS )
set(waffle_lab_DOC_DEPENDS )
set(waffle_lab_URL_WEBSITE "")
set(waffle_lab_URL_BUGTRACKER "")
set(waffle_lab_URL_REPOSITORY "")
set(waffle_lab_DEPRECATED "")